apiVersion: v1
kind: Secret
metadata:
  name: bot-nghi-phep-secret
  namespace: bot-nghi-phep
type: Opaque
stringData:
  DISCORD_TOKEN: "<THAY_BANG_TOKEN_THAT>"
  CLIENT_ID: "<THAY_BANG_CLIENT_ID>"
  NOTIFICATION_CHANNEL_ID: "<THAY_BANG_CHANNEL_ID>"
  GOOGLE_CALENDAR_ID: "<THAY_BANG_CALENDAR_ID>"
  GOOGLE_SERVICE_ACCOUNT_EMAIL: "<THAY_BANG_SERVICE_ACCOUNT>"
  GOOGLE_PRIVATE_KEY: "<THAY_BANG_PRIVATE_KEY>"
  GOOGLE_GEMINI_API_KEY: "<THAY_BANG_GEMINI_KEY>"
  GEMINI_MODEL: "gemini-3-flash-preview"
